// Builds apps-script/Code.gs: the page schema from js/schema.js followed by
// the server code in apps-script/src/server.js, as one file to paste into
// script.google.com.  Run: npm run build
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { PAGES } from '../js/schema.js';

export async function buildGas() {
  const server = await readFile(new URL('../apps-script/src/server.js', import.meta.url), 'utf8');
  return [
    '// WR server for Google Apps Script. Generated by scripts/build-gas.mjs: do not edit by hand;',
    '// change apps-script/src/server.js or js/schema.js and run `npm run build`.',
    '// How to install it: docs/SETUP-GOOGLE.md',
    '',
    `var SCHEMA = ${JSON.stringify({ pages: PAGES }, null, 2)};`,
    '',
    server,
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(new URL('../apps-script/Code.gs', import.meta.url), await buildGas());
  console.log('Wrote apps-script/Code.gs');
}
